spring:
  application:
    name: parking-application
    version: 1.0.0-SNAPSHOT
parking:
  basicParams:
    proportion: 2.75
    minLength: 0.00205
    defaultLength: 0.0205
  cities:
    - cityName: poitiers
      url: http://localhost:8090/demo/poitiers
      request:
        method: GET
        params:
          lattitude: lattitude
          longitude: longitude
          length: length
          proportion: proportion
      jsonItem: $.[*]
      item:
        name: name
        info: info
        lattitude: lattitude
        longitude: longitude
        capacity:
          name: capacity
          type: INTEGER
        freePlaces:
          name: free
          type: INTEGER
    - cityName: monpelliers
      url: http://localhost:8090/demo/montpellier/
      method: POST
      pathOrder: lattitudeMin, lattitudeMax, longitudeMin, longitudeMax
      params:
        type: PATH
        lattitudeMin: lat-min
        lattitudeMax: lat-max
        longitudeMin: lon-min
        longitudeMax: lon-max
      jsonItem: $.records[*].fields
      item:
        name: nom
        info: info
        lattitude: ylat
        longitude: xlong
        capacity:
          name: capacite
          type: DOUBLE
        freePlaces:
          name: places
          type: DOUBLE
