spring:
  application:
    name: parking
    version: 1.0.0-SNAPSHOT
    filter:
      path:
        included: /api/parking
server:
  port: 8100
  error:
    include-message: always
parking:
  basicParams:
    proportion: 2.75
    defaultLength: 0.0205
  cities:
    -
      cityName: poitiers
      url: http://localhost:8090/demo/poitiers
      method: GET
      authorizationType: NO_AUTH
      paramsType: PARAMS
      params:
        lattitude: lattitude
        longitude: longitude
        length: length
        proportion: proportion
      jsonItem: $.[*]
      items:
        NAME:
          name: name
          type: STRING
        INFO:
          name: info
          type: STRING
        LATTITUDE:
          name: lattitude
          type: DOUBLE
        LONGITUDE:
          name: longitude
          type: DOUBLE
        CAPACITY:
          name: capacity
          type: INTEGER
        FREE_PLACES:
          name: free
          type: INTEGER
    -
      cityName: montpellier
      url: http://localhost:8090/demo/montpellier/
      method: POST
      authorizationType: BEARER
      pathOrder: lattitudeMin, lattitudeMax, longitudeMin, longitudeMax
      paramsType: PATH
      params:
        lattitudeMin: lat-min
        lattitudeMax: lat-max
        longitudeMin: lon-min
        longitudeMax: lon-max
      jsonItem: $.records[*].fields
      items:
        NAME:
          name: nom
          type: STRING
        INFO:
          name: info
          type: STRING
        LATTITUDE:
          name: ylat
          type: DOUBLE
        LONGITUDE:
          name: xlong
          type: DOUBLE
        CAPACITY:
          name: capacite
          type: DOUBLE
        FREE_PLACES:
          name: places
          type: DOUBLE
